create table if not exists public.profiles (
	id uuid primary key references auth.users (id) on delete cascade,
	name text not null default 'NutriAI member',
	focus text not null default 'Balanced nutrition',
	goals jsonb not null default '{"calories":2050,"protein":120,"carbs":220,"fat":68}'::jsonb,
	profile_completed boolean not null default false,
	weight_goal text not null default 'Maintain weight'
		check (weight_goal in ('Weight loss', 'Maintain weight', 'Weight gain')),
	streak_days integer not null default 0 check (streak_days >= 0),
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

alter table public.profiles
	add column if not exists profile_completed boolean not null default false;

create table if not exists public.meals (
	id bigint generated by default as identity primary key,
	user_id uuid not null references auth.users (id) on delete cascade,
	name text not null,
	type text not null check (type in ('Breakfast', 'Lunch', 'Dinner', 'Snack')),
	time text not null,
	calories integer not null default 0 check (calories >= 0),
	protein integer not null default 0 check (protein >= 0),
	carbs integer not null default 0 check (carbs >= 0),
	fat integer not null default 0 check (fat >= 0),
	icon text not null default '🥗',
	image text,
	created_at timestamptz not null default now()
);

create table if not exists public.check_ins (
	user_id uuid not null references auth.users (id) on delete cascade,
	day date not null,
	created_at timestamptz not null default now(),
	primary key (user_id, day)
);

create table if not exists public.water_logs (
	user_id uuid not null references auth.users (id) on delete cascade,
	day date not null,
	glasses integer not null default 0 check (glasses >= 0 and glasses <= 40),
	updated_at timestamptz not null default now(),
	primary key (user_id, day)
);

create index if not exists meals_user_created_at_idx on public.meals (user_id, created_at desc);
create index if not exists check_ins_user_day_idx on public.check_ins (user_id, day desc);

alter table public.profiles enable row level security;
alter table public.meals enable row level security;
alter table public.check_ins enable row level security;
alter table public.water_logs enable row level security;

drop policy if exists profiles_owner_all on public.profiles;
create policy profiles_owner_all on public.profiles
	for all to authenticated
	using (id = (select auth.uid()))
	with check (id = (select auth.uid()));

drop policy if exists meals_owner_all on public.meals;
create policy meals_owner_all on public.meals
	for all to authenticated
	using (user_id = (select auth.uid()))
	with check (user_id = (select auth.uid()));

drop policy if exists check_ins_owner_all on public.check_ins;
create policy check_ins_owner_all on public.check_ins
	for all to authenticated
	using (user_id = (select auth.uid()))
	with check (user_id = (select auth.uid()));

drop policy if exists water_logs_owner_all on public.water_logs;
create policy water_logs_owner_all on public.water_logs
	for all to authenticated
	using (user_id = (select auth.uid()))
	with check (user_id = (select auth.uid()));

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.profiles, public.meals, public.check_ins, public.water_logs to authenticated;
grant usage, select on sequence public.meals_id_seq to authenticated;
